env:
   browser: true
   es2021: true
extends: ["plugin:react/recommended", "plugin:@typescript-eslint/recommended"]
overrides: []
parserOptions:
   project:
      - tsconfig.json
   ecmaVersion: latest
   sourceType: module
plugins: ["react", "@typescript-eslint"]

rules: { "react/react-in-jsx-scope": "off" }
