name: Deploy on merge to main
on:
  push:
    branches:
      - main
    paths:
    - 'src/**'
    - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on merge to main
    steps:
      - uses: actions/checkout@v3
      - run: git config --global user.email "juanky@novoda.com"
      - run: git config --global user.name "juankysoriano"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
 
      - name: Install dependencies
        working-directory: ./
        run: npm install

      - name: Build
        working-directory: ./
        run: npm run build

      - name: Deploy
        working-directory: ./
        run: npm run deploy
