name: Start scheduled job

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "30 14 * * mon"

jobs:
  cron:
    runs-on: ubuntu-latest
    name: Start the server
    steps:
      # TODO do something useful
      - name: Run a one-line script
        run: echo Hello, world!
