name: Stop scheduled job

on:
  # Triggers the workflow every monday at 16:00 UTC
  schedule:
    - cron: "0 16 * * mon"

jobs:
  cron:
    runs-on: ubuntu-latest
    name: Stop the server
    steps:
      # TODO do something useful
      - name: Run a one-line script
        run: echo Hello, world!
